name: ashker_crediting_solution
description: MVP for Ashker Crediting Shopping Solution
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  cloud_firestore: ^3.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"
