name: ashker_credit_app
description: A Flutter app for Ashker Credit Shopping Solution

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  http: ^0.14.0
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  dio: ^5.0.0
